### ISSUE TITLE
Collating Word Clouds

### ISSUE THREAD

**Issue by FitzKaos** [ContentMine/ami-plugin#24]
Hi, I think it would be a good idea if the individual word clouds generated could be collated together to create a descriptive word cloud for all the documents. Would this be possible?

Cheers!

**Comment by petermr** [comment]
This is possible within a `CProject`. word clouds for each `CTree` are in `words.frequencies.snippets.xml` and the wordcloud for the whole `CProject` is in:

```
words.frequencies.snippets.xml
```

If you want to mergs `CProject` clouds then we will need to devise a `CProject` merger / splitting strategy
