### ISSUE TITLE
Move to versioned releases

### ISSUE THREAD

**Issue by blahah** [ContentMine/ami-plugin#5]

**Comment by blahah** [comment]
Once binaries are being deployed with each versioned release, we should update the workshop docs to describe how to get them. See https://github.com/ContentMine/workshops/issues/16

**Comment by tarrow** [comment]
I am now actively working on this issue. We hope to move to properly versioned releases in the next few weeks.

**Comment by tarrow** [comment]
We do now have versioned releases on github. We need to move to proper versioning in the POM so that we have versions on the maven repository.
