### ISSUE TITLE
Prune unnecessary code/content

### ISSUE THREAD

**Issue by blahah** [ContentMine/ami-plugin#6]
There are some directories and files that may not need to be a part of this repo. We should eliminate them early.

We can use this thread to highlight files and discuss whether they should be kept. Once a list of files to remove is drawn up, I will prune them in a pull request.

**Comment by blahah** [comment]
https://github.com/ContentMine/ami-plugin/tree/master/cochrane

This directory seems like it belongs in a workshop-specific repo and is not part of `ami` generally - @petermr can you confirm?

**Comment by blahah** [comment]
The same goes for https://github.com/ContentMine/ami-plugin/tree/master/examplestemp and https://github.com/ContentMine/ami-plugin/tree/master/examples. If the intention is to include some test files with the repo - perhaps we can package them separately, host them outside of the source control, and then include them in the instructions. @petermr thoughts?

**Comment by blahah** [comment]
There are a lot of files in the root, e.g.:
- `BUILDING.md`
- `EXAMPLES.md`
- `REGEX.md`

etc. It seems to me that these belong in the `/docs` directory, and that the things currently in `/docs` are perhaps not required any longer. Perhaps it would also make sense to move the two example scripts into either `/examples` (if we keep that dir) or `/docs`.

**Comment by blahah** [comment]
I think the `/regex` dir (https://github.com/ContentMine/ami-plugin/tree/master/regex) should perhaps be in the resources, rather than the root. Does this seem right @petermr?

**Comment by petermr** [comment]
I dithered about this. It's meant to be easy to find for users, whereas
src/main/resources ... is more hidden. Half of them are experimental and
maybe most of them will decay. Because regexes can be located by absolute
file or URL they could be anywhere. Need to discuss some time.

On Thu, Mar 26, 2015 at 10:52 PM, Richard Smith-Unna <
notifications@github.com> wrote:

> I think the /regex dir (
> https://github.com/ContentMine/ami-plugin/tree/master/regex) should
> perhaps be in the resources, rather than the root. Does this seem right
> @petermr https://github.com/petermr?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContentMine/ami-plugin/issues/6#issuecomment-86745368
> .

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by petermr** [comment]
Yes , it needs hacking

On Thu, Mar 26, 2015 at 10:52 PM, Richard Smith-Unna <
notifications@github.com> wrote:

> There are a lot of files in the root, e.g.:
> - BUILDING.md
> - EXAMPLES.md
> - REGEX.md
> 
> etc. It seems to me that these belong in the /docs directory, and that
> the things currently in /docs are perhaps not required any longer.
> Perhaps it would also make sense to move the two example scripts into
> either /examples (if we keep that dir) or /docs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContentMine/ami-plugin/issues/6#issuecomment-86745116
> .

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by petermr** [comment]
It's not really for another workshop - they are good example. They could
get put under src/test/resources ...

On Thu, Mar 26, 2015 at 10:34 PM, Richard Smith-Unna <
notifications@github.com> wrote:

> The same goes for
> https://github.com/ContentMine/ami-plugin/tree/master/examplestemp and
> https://github.com/ContentMine/ami-plugin/tree/master/examples. If the
> intention is to include some test files with the repo - perhaps we can
> package them separately, host them outside of the source control, and then
> include them in the instructions. @petermr https://github.com/petermr
> thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContentMine/ami-plugin/issues/6#issuecomment-86741574
> .

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by petermr** [comment]
I think if the word "Cochrane" is removed and replaced by example/tutorial
then it fits

On Thu, Mar 26, 2015 at 10:33 PM, Richard Smith-Unna <
notifications@github.com> wrote:

> https://github.com/ContentMine/ami-plugin/tree/master/cochrane
> 
> This directory seems like it belongs in a workshop-specific repo and is
> not part of ami generally - @petermr https://github.com/petermr can you
> confirm?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContentMine/ami-plugin/issues/6#issuecomment-86741187
> .

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069
